kind: Service
apiVersion: v1
metadata:
  name: nr-exp-app1-svc
spec:
  selector:
    app: nr-exp-app1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8088

---
kind: Service
apiVersion: v1
metadata:
  name: nr-exp-app2-svc
spec:
  selector:
    app: nr-exp-app2
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8088
