apiVersion: argoproj.io/v1alpha1
kind: Experiment
metadata:
  name: oes-issuegen-exp1
spec:
  duration: 5m
  progressDeadlineSeconds: 30
  templates:
  - name: baseline
    specRef: stable
    replicas: 1
    spec:
      containers:
        - name: rollouts-baseline
          image: argoproj/rollouts-demo:orange
          imagePullPolicy: Always
          ports:
            - containerPort: 8088
  - name: canary
    specRef: canary
    replicas: 1
    spec:
      containers:
        - name: rollouts-baseline
          image: argoproj/rollouts-demo:purple
          imagePullPolicy: Always
          ports:
            - containerPort: 8088
    
            
  # List of AnalysisTemplate references to perform during the experiment
  analyses:
  - name: analysisTemplateV1
    templateName: analysisTemplateV1
