apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: mann-whitney
spec:
  args:
  - name: start-time
  - name: end-time
  metrics:
  - name: bucket-rate
    provider:
      kayenta:
        address: https://1f4d-122-166-128-163.in.ngrok.io
        application: prom-test-app
        canaryConfigName: prom-config-argo
        metricsAccountName: my-prometheus-account
        storageAccountName: in-memory-store-account
        configurationAccountName: in-memory-store-account
        threshold:
          pass: 90
          marginal: 75
        scopes:
        - name: default
          controlScope:
            scope: default
            step: 60
            start: "{{args.start-time}}"
            end: "{{args.end-time}}"
          experimentScope:
            scope: default
            step: 60
            start: "{{args.start-time}}"
            end: "{{args.end-time}}"
